In [252]:
from lxml import etree
import pandas as pd

## schedule

In [253]:
parser = etree.XMLParser(encoding="euc-kr")
tree = etree.parse('C:\\Develop\\Project7\\dataset\\schedule2022120221019212245.xml', parser=parser)


pageIds = tree.find('row')
schedule = pd.DataFrame(columns = [x[0] for x in pageIds.items()])
pageIds = tree.findall('row')
for page in pageIds:
    mydict = dict(page.items())
    condf = pd.DataFrame.from_dict(mydict, orient='index').T
    schedule = pd.concat([schedule, condf], ignore_index=True)

schedule

,meet_year,meet_seq,meet_name,game_id,game_date,yoil,game_time,home_team,home_team_name,home_team_goal,home_team_tk,away_team,away_team_name,away_team_goal,away_team_tk,field_id,field_name,game_type,game_type_name,audience
0,2022,1,하나원큐 K리그1 2022,1,2022/02/19,토,14:00,K05,전북,1,0,K29,수원FC,0,0,71,전주W,21,스플릿일반,7715
1,2022,1,하나원큐 K리그1 2022,2,2022/02/19,토,16:30,K17,대구,0,0,K09,서울,2,0,114,대구전,21,스플릿일반,8082
2,2022,1,하나원큐 K리그1 2022,3,2022/02/19,토,16:30,K18,인천,1,0,K02,수원,0,0,95,인천,21,스플릿일반,5382
3,2022,1,하나원큐 K리그1 2022,4,2022/02/20,일,14:00,K04,제주,0,0,K03,포항,3,0,85,제주W,21,스플릿일반,2514
4,2022,1,하나원큐 K리그1 2022,5,2022/02/20,일,14:00,K21,강원,2,0,K08,성남,0,0,25,강릉,21,스플릿일반,1933
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
223,2022,1,하나원큐 K리그1 2022,224,2022/10/22,토,15:00,K35,김천,NaN,NaN,K02,수원,NaN,NaN,118,김천,24,파이널B,0
224,2022,1,하나원큐 K리그1 2022,225,2022/10/22,토,15:00,K08,성남,NaN,NaN,K17,대구,NaN,NaN,84,탄천,24,파이널B,0
225,2022,1,하나원큐 K리그1 2022,226,2022/10/23,일,15:00,K01,울산,NaN,NaN,K04,제주,NaN,NaN,68,문수,23,파이널A,0
226,2022,1,하나원큐 K리그1 2022,227,2022/10/23,일,15:00,K05,전북,NaN,NaN,K18,인천,NaN,NaN,71,전주W,23,파이널A,0
227,2022,1,하나원큐 K리그1 2022,228,2022/10/23,일,15:00,K03,포항,NaN,NaN,K21,강원,NaN,NaN,14,포항,23,파이널A,0

In [254]:
schedule.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 228 entries, 0 to 227
Data columns (total 20 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   meet_year       228 non-null    object
 1   meet_seq        228 non-null    object
 2   meet_name       228 non-null    object
 3   game_id         228 non-null    object
 4   game_date       228 non-null    object
 5   yoil            228 non-null    object
 6   game_time       228 non-null    object
 7   home_team       228 non-null    object
 8   home_team_name  228 non-null    object
 9   home_team_goal  222 non-null    object
 10  home_team_tk    222 non-null    object
 11  away_team       228 non-null    object
 12  away_team_name  228 non-null    object
 13  away_team_goal  222 non-null    object
 14  away_team_tk    222 non-null    object
 15  field_id        228 non-null    object
 16  field_name      228 non-null    object
 17  game_type       228 non-null    object
 18  game_type_name  228 non-null    object
 19  audience        228 non-null    object
dtypes: object(20)
memory usage: 35.8+ KB

# drop columns
meet_year, meet_seq, meet_name / 단일값<br>
home_team / home_team_name 대체<br>
away_team / away_team_name 대체<br>
field_id / field_name 대체<br>
game_type / game_type_name 대체

In [255]:
schedule = schedule.drop(columns=['meet_year', 'meet_seq', 'meet_name', 'home_team', 'away_team', 'field_id', 'game_type'])

In [256]:
schedule

,game_id,game_date,yoil,game_time,home_team_name,home_team_goal,home_team_tk,away_team_name,away_team_goal,away_team_tk,field_name,game_type_name,audience
0,1,2022/02/19,토,14:00,전북,1,0,수원FC,0,0,전주W,스플릿일반,7715
1,2,2022/02/19,토,16:30,대구,0,0,서울,2,0,대구전,스플릿일반,8082
2,3,2022/02/19,토,16:30,인천,1,0,수원,0,0,인천,스플릿일반,5382
3,4,2022/02/20,일,14:00,제주,0,0,포항,3,0,제주W,스플릿일반,2514
4,5,2022/02/20,일,14:00,강원,2,0,성남,0,0,강릉,스플릿일반,1933
...,...,...,...,...,...,...,...,...,...,...,...,...,...
223,224,2022/10/22,토,15:00,김천,NaN,NaN,수원,NaN,NaN,김천,파이널B,0
224,225,2022/10/22,토,15:00,성남,NaN,NaN,대구,NaN,NaN,탄천,파이널B,0
225,226,2022/10/23,일,15:00,울산,NaN,NaN,제주,NaN,NaN,문수,파이널A,0
226,227,2022/10/23,일,15:00,전북,NaN,NaN,인천,NaN,NaN,전주W,파이널A,0
227,228,2022/10/23,일,15:00,포항,NaN,NaN,강원,NaN,NaN,포항,파이널A,0

In [257]:
schedule = schedule[(schedule['home_team_name']=='인천') | (schedule['away_team_name']=='인천')] # 클라이언트의 경기일정만 추출
schedule = schedule.dropna() # 관중수 0인 결측데이터로 현 경기결과를 찾아보면서까지 활용할 가치가 없음
schedule

,game_id,game_date,yoil,game_time,home_team_name,home_team_goal,home_team_tk,away_team_name,away_team_goal,away_team_tk,field_name,game_type_name,audience
2,3,2022/02/19,토,16:30,인천,1,0,수원,0,0,인천,스플릿일반,5382
7,8,2022/02/26,토,14:00,인천,1,0,서울,1,0,인천,스플릿일반,4618
15,16,2022/03/01,화,16:30,강원,0,0,인천,1,0,강릉,스플릿일반,1559
20,21,2022/03/05,토,19:00,인천,0,0,포항,1,0,인천,스플릿일반,3581
28,29,2022/03/13,일,14:00,인천,1,0,김천,0,0,인천,스플릿일반,2607
34,36,2022/03/20,일,19:00,성남,0,0,인천,1,0,탄천,스플릿일반,1361
37,38,2022/04/02,토,14:00,인천,1,0,울산,1,0,인천,스플릿일반,7054
43,44,2022/04/05,화,19:30,대구,1,0,인천,2,0,대구전,스플릿일반,3009
52,53,2022/04/10,일,16:30,인천,2,0,제주,2,0,인천,스플릿일반,5234
58,59,2022/05/05,목,19:00,수원FC,2,0,인천,2,0,수원,스플릿일반,3794
63,64,2022/05/08,일,16:30,인천,0,0,전북,1,0,인천,스플릿일반,7597
67,68,2022/05/14,토,19:00,울산,2,0,인천,2,0,문수,스플릿일반,8351
73,74,2022/05/17,화,19:30,인천,2,0,대구,2,0,인천,스플릿일반,2754
79,80,2022/05/21,토,18:00,포항,2,0,인천,0,0,포항,스플릿일반,4824
87,88,2022/05/29,일,16:30,인천,1,0,성남,0,0,인천,스플릿일반,6119
92,93,2022/06/18,토,18:00,제주,2,0,인천,1,0,제주W,스플릿일반,4155
101,102,2022/06/22,수,19:30,인천,4,0,강원,1,0,인천,스플릿일반,2509
104,105,2022/06/25,토,20:00,서울,1,0,인천,1,0,서울W,스플릿일반,10787
113,114,2022/07/03,일,19:30,수원,0,0,인천,0,0,수원W,스플릿일반,4325
118,119,2022/07/06,수,19:00,인천,0,0,수원FC,1,0,인천,스플릿일반,3647
122,123,2022/07/09,토,19:00,전북,2,0,인천,2,0,전주W,스플릿일반,6666
128,129,2022/07/16,토,18:00,김천,0,0,인천,1,0,김천,스플릿일반,1096
136,149,2022/07/30,토,20:00,성남,3,0,인천,1,0,탄천,스플릿일반,1861
141,154,2022/08/03,수,19:00,인천,1,0,수원FC,1,0,인천,스플릿일반,3731
149,162,2022/08/07,일,19:30,대구,2,0,인천,3,0,대구전,스플릿일반,6336
153,164,2022/08/13,토,19:30,인천,3,0,전북,1,0,인천,스플릿일반,6339
159,144,2022/08/20,토,18:00,포항,1,0,인천,1,0,포항,스플릿일반,3479
164,138,2022/08/27,토,20:00,인천,2,0,서울,0,0,인천,스플릿일반,10139
169,170,2022/09/02,금,19:30,인천,0,0,강원,1,0,인천,스플릿일반,4372
174,175,2022/09/06,화,19:00,제주,0,0,인천,1,0,제주W,스플릿일반,1688
185,186,2022/09/11,일,19:00,수원,3,0,인천,3,0,수원W,스플릿일반,8491
190,191,2022/09/14,수,19:00,인천,0,0,울산,0,0,인천,스플릿일반,4472
197,198,2022/09/18,일,15:00,김천,1,0,인천,0,0,김천,스플릿일반,1260
199,200,2022/10/01,토,16:30,인천,0,0,울산,3,0,인천,파이널A,9251
206,207,2022/10/08,토,19:00,강원,0,0,인천,0,0,춘천,파이널A,3751
212,213,2022/10/11,화,19:30,인천,3,0,제주,1,0,인천,파이널A,2970
220,221,2022/10/16,일,19:00,인천,1,0,포항,1,0,인천,파이널A,7592

In [258]:
schedule['home'] = schedule['home_team_name'] == '인천' # home adv
schedule.reset_index(drop=True, inplace=True)

In [259]:
opp = []
for i in range(len(schedule)):
    if schedule.home.loc[i] == True:
        opp.append(schedule.away_team_name.loc[i])
    else:
        opp.append(schedule.home_team_name.loc[i])
schedule['opponent'] = pd.Series(data=opp)  # vs team

In [260]:
goal_incheon = []
goal_diff = []
for i in range(len(schedule)):
    if schedule.home.loc[i] == True:
        goal_incheon.append(schedule.home_team_goal.loc[i])
        goal_diff.append(int(schedule.home_team_goal.loc[i]) - int(schedule.away_team_goal.loc[i]))
    else:
        goal_incheon.append(schedule.away_team_goal.loc[i])
        goal_diff.append(int(schedule.away_team_goal.loc[i]) - int(schedule.home_team_goal.loc[i]))
schedule['goal_incheon'] = pd.Series(data=goal_incheon)  # 인천 득점
schedule['goal_diff'] = pd.Series(data=goal_diff)  # 상대와의 득점차(양수 = 승리, 음수 = 패배)

In [261]:
schedule.away_team_tk.unique() # 승부차기 X

array(['0'], dtype=object)

In [262]:
schedule # 중간확인

,game_id,game_date,yoil,game_time,home_team_name,home_team_goal,home_team_tk,away_team_name,away_team_goal,away_team_tk,field_name,game_type_name,audience,home,opponent,goal_incheon,goal_diff
0,3,2022/02/19,토,16:30,인천,1,0,수원,0,0,인천,스플릿일반,5382,True,수원,1,1
1,8,2022/02/26,토,14:00,인천,1,0,서울,1,0,인천,스플릿일반,4618,True,서울,1,0
2,16,2022/03/01,화,16:30,강원,0,0,인천,1,0,강릉,스플릿일반,1559,False,강원,1,1
3,21,2022/03/05,토,19:00,인천,0,0,포항,1,0,인천,스플릿일반,3581,True,포항,0,-1
4,29,2022/03/13,일,14:00,인천,1,0,김천,0,0,인천,스플릿일반,2607,True,김천,1,1
5,36,2022/03/20,일,19:00,성남,0,0,인천,1,0,탄천,스플릿일반,1361,False,성남,1,1
6,38,2022/04/02,토,14:00,인천,1,0,울산,1,0,인천,스플릿일반,7054,True,울산,1,0
7,44,2022/04/05,화,19:30,대구,1,0,인천,2,0,대구전,스플릿일반,3009,False,대구,2,1
8,53,2022/04/10,일,16:30,인천,2,0,제주,2,0,인천,스플릿일반,5234,True,제주,2,0
9,59,2022/05/05,목,19:00,수원FC,2,0,인천,2,0,수원,스플릿일반,3794,False,수원FC,2,0
10,64,2022/05/08,일,16:30,인천,0,0,전북,1,0,인천,스플릿일반,7597,True,전북,0,-1
11,68,2022/05/14,토,19:00,울산,2,0,인천,2,0,문수,스플릿일반,8351,False,울산,2,0
12,74,2022/05/17,화,19:30,인천,2,0,대구,2,0,인천,스플릿일반,2754,True,대구,2,0
13,80,2022/05/21,토,18:00,포항,2,0,인천,0,0,포항,스플릿일반,4824,False,포항,0,-2
14,88,2022/05/29,일,16:30,인천,1,0,성남,0,0,인천,스플릿일반,6119,True,성남,1,1
15,93,2022/06/18,토,18:00,제주,2,0,인천,1,0,제주W,스플릿일반,4155,False,제주,1,-1
16,102,2022/06/22,수,19:30,인천,4,0,강원,1,0,인천,스플릿일반,2509,True,강원,4,3
17,105,2022/06/25,토,20:00,서울,1,0,인천,1,0,서울W,스플릿일반,10787,False,서울,1,0
18,114,2022/07/03,일,19:30,수원,0,0,인천,0,0,수원W,스플릿일반,4325,False,수원,0,0
19,119,2022/07/06,수,19:00,인천,0,0,수원FC,1,0,인천,스플릿일반,3647,True,수원FC,0,-1
20,123,2022/07/09,토,19:00,전북,2,0,인천,2,0,전주W,스플릿일반,6666,False,전북,2,0
21,129,2022/07/16,토,18:00,김천,0,0,인천,1,0,김천,스플릿일반,1096,False,김천,1,1
22,149,2022/07/30,토,20:00,성남,3,0,인천,1,0,탄천,스플릿일반,1861,False,성남,1,-2
23,154,2022/08/03,수,19:00,인천,1,0,수원FC,1,0,인천,스플릿일반,3731,True,수원FC,1,0
24,162,2022/08/07,일,19:30,대구,2,0,인천,3,0,대구전,스플릿일반,6336,False,대구,3,1
25,164,2022/08/13,토,19:30,인천,3,0,전북,1,0,인천,스플릿일반,6339,True,전북,3,2
26,144,2022/08/20,토,18:00,포항,1,0,인천,1,0,포항,스플릿일반,3479,False,포항,1,0
27,138,2022/08/27,토,20:00,인천,2,0,서울,0,0,인천,스플릿일반,10139,True,서울,2,2
28,170,2022/09/02,금,19:30,인천,0,0,강원,1,0,인천,스플릿일반,4372,True,강원,0,-1
29,175,2022/09/06,화,19:00,제주,0,0,인천,1,0,제주W,스플릿일반,1688,False,제주,1,1
30,186,2022/09/11,일,19:00,수원,3,0,인천,3,0,수원W,스플릿일반,8491,False,수원,3,0
31,191,2022/09/14,수,19:00,인천,0,0,울산,0,0,인천,스플릿일반,4472,True,울산,0,0
32,198,2022/09/18,일,15:00,김천,1,0,인천,0,0,김천,스플릿일반,1260,False,김천,0,-1
33,200,2022/10/01,토,16:30,인천,0,0,울산,3,0,인천,파이널A,9251,True,울산,0,-3
34,207,2022/10/08,토,19:00,강원,0,0,인천,0,0,춘천,파이널A,3751,False,강원,0,0
35,213,2022/10/11,화,19:30,인천,3,0,제주,1,0,인천,파이널A,2970,True,제주,3,2
36,221,2022/10/16,일,19:00,인천,1,0,포항,1,0,인천,파이널A,7592,True,포항,1,0

# drop columns Ⅱ
game_id / 분석에 필요없는 특성<br>
home_team_name, away_team_name / home, opponent로 대체<br>
home_team_tk, away_team_tk / 승부차기 없었으므로 제거<br>
home_team_goal, away_team_goal / 클라이언트의 골(goal_incheon)과 골 득실차(goal_diff)로 대체

In [263]:
schedule = schedule.drop(columns=['game_id','home_team_name','home_team_goal','home_team_tk','away_team_name','away_team_goal','away_team_tk'])
schedule

,game_date,yoil,game_time,field_name,game_type_name,audience,home,opponent,goal_incheon,goal_diff
0,2022/02/19,토,16:30,인천,스플릿일반,5382,True,수원,1,1
1,2022/02/26,토,14:00,인천,스플릿일반,4618,True,서울,1,0
2,2022/03/01,화,16:30,강릉,스플릿일반,1559,False,강원,1,1
3,2022/03/05,토,19:00,인천,스플릿일반,3581,True,포항,0,-1
4,2022/03/13,일,14:00,인천,스플릿일반,2607,True,김천,1,1
5,2022/03/20,일,19:00,탄천,스플릿일반,1361,False,성남,1,1
6,2022/04/02,토,14:00,인천,스플릿일반,7054,True,울산,1,0
7,2022/04/05,화,19:30,대구전,스플릿일반,3009,False,대구,2,1
8,2022/04/10,일,16:30,인천,스플릿일반,5234,True,제주,2,0
9,2022/05/05,목,19:00,수원,스플릿일반,3794,False,수원FC,2,0
10,2022/05/08,일,16:30,인천,스플릿일반,7597,True,전북,0,-1
11,2022/05/14,토,19:00,문수,스플릿일반,8351,False,울산,2,0
12,2022/05/17,화,19:30,인천,스플릿일반,2754,True,대구,2,0
13,2022/05/21,토,18:00,포항,스플릿일반,4824,False,포항,0,-2
14,2022/05/29,일,16:30,인천,스플릿일반,6119,True,성남,1,1
15,2022/06/18,토,18:00,제주W,스플릿일반,4155,False,제주,1,-1
16,2022/06/22,수,19:30,인천,스플릿일반,2509,True,강원,4,3
17,2022/06/25,토,20:00,서울W,스플릿일반,10787,False,서울,1,0
18,2022/07/03,일,19:30,수원W,스플릿일반,4325,False,수원,0,0
19,2022/07/06,수,19:00,인천,스플릿일반,3647,True,수원FC,0,-1
20,2022/07/09,토,19:00,전주W,스플릿일반,6666,False,전북,2,0
21,2022/07/16,토,18:00,김천,스플릿일반,1096,False,김천,1,1
22,2022/07/30,토,20:00,탄천,스플릿일반,1861,False,성남,1,-2
23,2022/08/03,수,19:00,인천,스플릿일반,3731,True,수원FC,1,0
24,2022/08/07,일,19:30,대구전,스플릿일반,6336,False,대구,3,1
25,2022/08/13,토,19:30,인천,스플릿일반,6339,True,전북,3,2
26,2022/08/20,토,18:00,포항,스플릿일반,3479,False,포항,1,0
27,2022/08/27,토,20:00,인천,스플릿일반,10139,True,서울,2,2
28,2022/09/02,금,19:30,인천,스플릿일반,4372,True,강원,0,-1
29,2022/09/06,화,19:00,제주W,스플릿일반,1688,False,제주,1,1
30,2022/09/11,일,19:00,수원W,스플릿일반,8491,False,수원,3,0
31,2022/09/14,수,19:00,인천,스플릿일반,4472,True,울산,0,0
32,2022/09/18,일,15:00,김천,스플릿일반,1260,False,김천,0,-1
33,2022/10/01,토,16:30,인천,파이널A,9251,True,울산,0,-3
34,2022/10/08,토,19:00,춘천,파이널A,3751,False,강원,0,0
35,2022/10/11,화,19:30,인천,파이널A,2970,True,제주,3,2
36,2022/10/16,일,19:00,인천,파이널A,7592,True,포항,1,0

휴일과의 연관성 분석을 위한 특성조율

In [264]:
schedule['game_date'] = pd.to_datetime(schedule['game_date'])
schedule.rename(columns={'game_date':'date', 'yoil':'weekday'}, inplace=True)
schedule.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            37 non-null     datetime64[ns]
 1   weekday         37 non-null     object
 2   game_time       37 non-null     object
 3   field_name      37 non-null     object
 4   game_type_name  37 non-null     object
 5   audience        37 non-null     object
 6   home            37 non-null     bool
 7   opponent        37 non-null     object
 8   goal_incheon    37 non-null     object
 9   goal_diff       37 non-null     int64
dtypes: bool(1), datetime64[ns](1), int64(1), object(7)
memory usage: 2.8+ KB

In [265]:
import datetime
import requests
from bs4 import BeautifulSoup, element

In [266]:
def getHolidayDataFrame(year: int) -> pd.DataFrame:
    url = 'http://apis.data.go.kr/B090041/openapi/service/SpcdeInfoService/getRestDeInfo'
    api_key = 'YeSiYlUdLxSa9aOaPFM1kADTX45LzrMBd%2F43zl9fzjusryc9kIaewAPe9FmIZU5h09iiB4SFHX1UKe9jLQcSRw%3D%3D'
    api_key_decoded = requests.utils.unquote(api_key, encoding='utf-8')

    params = {
        'serviceKey': api_key_decoded,
        'solYear': year,
        'numOfRows': 100
    }

    weekday_name = ['월','화','수','목','금','토','일']

    res = requests.get(url,params=params)
    xml = BeautifulSoup(res.text, features="lxml")

    def parseItem(item: element.Tag) -> dict:
        dt = datetime.datetime.strptime(item.find('locdate').text.strip(), '%Y%m%d')
        item_dict = {
            'name': item.find('datename').text.strip(),
            'date': dt,
            'weekday': weekday_name[dt.weekday()]
        }
        return item_dict

    item_list = [parseItem(x) for x in xml.find('items')]
    return pd.DataFrame(item_list)

In [267]:
holiday = getHolidayDataFrame(2022) # 공휴일
holiday

c:\Users\efoxh\anaconda3\envs\cp2\Lib\site-packages\bs4\builder\__init__.py:545: XMLParsedAsHTMLWarning: It looks like you're parsing an XML document using an HTML parser. If this really is an HTML document (maybe it's XHTML?), you can ignore or filter this warning. If it's XML, you should know that using an XML parser will be more reliable. To parse this document as XML, make sure you have the lxml package installed, and pass the keyword argument `features="xml"` into the BeautifulSoup constructor.
  warnings.warn(

        name       date weekday
0       1월1일 2022-01-01       토
1         설날 2022-01-31       월
2         설날 2022-02-01       화
3         설날 2022-02-02       수
4        삼일절 2022-03-01       화
5     대통령선거일 2022-03-09       수
6       어린이날 2022-05-05       목
7     부처님오신날 2022-05-08       일
8   전국동시지방선거 2022-06-01       수
9        현충일 2022-06-06       월
10       광복절 2022-08-15       월
11        추석 2022-09-09       금
12        추석 2022-09-10       토
13        추석 2022-09-11       일
14     대체공휴일 2022-09-12       월
15       개천절 2022-10-03       월
16       한글날 2022-10-09       일
17     대체공휴일 2022-10-10       월
18     기독탄신일 2022-12-25       일

In [268]:
schedule = pd.merge(schedule, holiday, how='left', on=['date','weekday'])
schedule

,date,weekday,game_time,field_name,game_type_name,audience,home,opponent,goal_incheon,goal_diff,name
0,2022-02-19,토,16:30,인천,스플릿일반,5382,True,수원,1,1,NaN
1,2022-02-26,토,14:00,인천,스플릿일반,4618,True,서울,1,0,NaN
2,2022-03-01,화,16:30,강릉,스플릿일반,1559,False,강원,1,1,삼일절
3,2022-03-05,토,19:00,인천,스플릿일반,3581,True,포항,0,-1,NaN
4,2022-03-13,일,14:00,인천,스플릿일반,2607,True,김천,1,1,NaN
5,2022-03-20,일,19:00,탄천,스플릿일반,1361,False,성남,1,1,NaN
6,2022-04-02,토,14:00,인천,스플릿일반,7054,True,울산,1,0,NaN
7,2022-04-05,화,19:30,대구전,스플릿일반,3009,False,대구,2,1,NaN
8,2022-04-10,일,16:30,인천,스플릿일반,5234,True,제주,2,0,NaN
9,2022-05-05,목,19:00,수원,스플릿일반,3794,False,수원FC,2,0,어린이날
10,2022-05-08,일,16:30,인천,스플릿일반,7597,True,전북,0,-1,부처님오신날
11,2022-05-14,토,19:00,문수,스플릿일반,8351,False,울산,2,0,NaN
12,2022-05-17,화,19:30,인천,스플릿일반,2754,True,대구,2,0,NaN
13,2022-05-21,토,18:00,포항,스플릿일반,4824,False,포항,0,-2,NaN
14,2022-05-29,일,16:30,인천,스플릿일반,6119,True,성남,1,1,NaN
15,2022-06-18,토,18:00,제주W,스플릿일반,4155,False,제주,1,-1,NaN
16,2022-06-22,수,19:30,인천,스플릿일반,2509,True,강원,4,3,NaN
17,2022-06-25,토,20:00,서울W,스플릿일반,10787,False,서울,1,0,NaN
18,2022-07-03,일,19:30,수원W,스플릿일반,4325,False,수원,0,0,NaN
19,2022-07-06,수,19:00,인천,스플릿일반,3647,True,수원FC,0,-1,NaN
20,2022-07-09,토,19:00,전주W,스플릿일반,6666,False,전북,2,0,NaN
21,2022-07-16,토,18:00,김천,스플릿일반,1096,False,김천,1,1,NaN
22,2022-07-30,토,20:00,탄천,스플릿일반,1861,False,성남,1,-2,NaN
23,2022-08-03,수,19:00,인천,스플릿일반,3731,True,수원FC,1,0,NaN
24,2022-08-07,일,19:30,대구전,스플릿일반,6336,False,대구,3,1,NaN
25,2022-08-13,토,19:30,인천,스플릿일반,6339,True,전북,3,2,NaN
26,2022-08-20,토,18:00,포항,스플릿일반,3479,False,포항,1,0,NaN
27,2022-08-27,토,20:00,인천,스플릿일반,10139,True,서울,2,2,NaN
28,2022-09-02,금,19:30,인천,스플릿일반,4372,True,강원,0,-1,NaN
29,2022-09-06,화,19:00,제주W,스플릿일반,1688,False,제주,1,1,NaN
30,2022-09-11,일,19:00,수원W,스플릿일반,8491,False,수원,3,0,추석
31,2022-09-14,수,19:00,인천,스플릿일반,4472,True,울산,0,0,NaN
32,2022-09-18,일,15:00,김천,스플릿일반,1260,False,김천,0,-1,NaN
33,2022-10-01,토,16:30,인천,파이널A,9251,True,울산,0,-3,NaN
34,2022-10-08,토,19:00,춘천,파이널A,3751,False,강원,0,0,NaN
35,2022-10-11,화,19:30,인천,파이널A,2970,True,제주,3,2,NaN
36,2022-10-16,일,19:00,인천,파이널A,7592,True,포항,1,0,NaN

In [269]:
for i in range(len(schedule)):
    if ~schedule.name.isnull().iloc[i]:
        schedule.weekday.iloc[i] = '공휴일'
schedule

C:\Users\efoxh\AppData\Local\Temp\ipykernel_26160\2229405489.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  schedule.weekday.iloc[i] = '공휴일'

,date,weekday,game_time,field_name,game_type_name,audience,home,opponent,goal_incheon,goal_diff,name
0,2022-02-19,토,16:30,인천,스플릿일반,5382,True,수원,1,1,NaN
1,2022-02-26,토,14:00,인천,스플릿일반,4618,True,서울,1,0,NaN
2,2022-03-01,공휴일,16:30,강릉,스플릿일반,1559,False,강원,1,1,삼일절
3,2022-03-05,토,19:00,인천,스플릿일반,3581,True,포항,0,-1,NaN
4,2022-03-13,일,14:00,인천,스플릿일반,2607,True,김천,1,1,NaN
5,2022-03-20,일,19:00,탄천,스플릿일반,1361,False,성남,1,1,NaN
6,2022-04-02,토,14:00,인천,스플릿일반,7054,True,울산,1,0,NaN
7,2022-04-05,화,19:30,대구전,스플릿일반,3009,False,대구,2,1,NaN
8,2022-04-10,일,16:30,인천,스플릿일반,5234,True,제주,2,0,NaN
9,2022-05-05,공휴일,19:00,수원,스플릿일반,3794,False,수원FC,2,0,어린이날
10,2022-05-08,공휴일,16:30,인천,스플릿일반,7597,True,전북,0,-1,부처님오신날
11,2022-05-14,토,19:00,문수,스플릿일반,8351,False,울산,2,0,NaN
12,2022-05-17,화,19:30,인천,스플릿일반,2754,True,대구,2,0,NaN
13,2022-05-21,토,18:00,포항,스플릿일반,4824,False,포항,0,-2,NaN
14,2022-05-29,일,16:30,인천,스플릿일반,6119,True,성남,1,1,NaN
15,2022-06-18,토,18:00,제주W,스플릿일반,4155,False,제주,1,-1,NaN
16,2022-06-22,수,19:30,인천,스플릿일반,2509,True,강원,4,3,NaN
17,2022-06-25,토,20:00,서울W,스플릿일반,10787,False,서울,1,0,NaN
18,2022-07-03,일,19:30,수원W,스플릿일반,4325,False,수원,0,0,NaN
19,2022-07-06,수,19:00,인천,스플릿일반,3647,True,수원FC,0,-1,NaN
20,2022-07-09,토,19:00,전주W,스플릿일반,6666,False,전북,2,0,NaN
21,2022-07-16,토,18:00,김천,스플릿일반,1096,False,김천,1,1,NaN
22,2022-07-30,토,20:00,탄천,스플릿일반,1861,False,성남,1,-2,NaN
23,2022-08-03,수,19:00,인천,스플릿일반,3731,True,수원FC,1,0,NaN
24,2022-08-07,일,19:30,대구전,스플릿일반,6336,False,대구,3,1,NaN
25,2022-08-13,토,19:30,인천,스플릿일반,6339,True,전북,3,2,NaN
26,2022-08-20,토,18:00,포항,스플릿일반,3479,False,포항,1,0,NaN
27,2022-08-27,토,20:00,인천,스플릿일반,10139,True,서울,2,2,NaN
28,2022-09-02,금,19:30,인천,스플릿일반,4372,True,강원,0,-1,NaN
29,2022-09-06,화,19:00,제주W,스플릿일반,1688,False,제주,1,1,NaN
30,2022-09-11,공휴일,19:00,수원W,스플릿일반,8491,False,수원,3,0,추석
31,2022-09-14,수,19:00,인천,스플릿일반,4472,True,울산,0,0,NaN
32,2022-09-18,일,15:00,김천,스플릿일반,1260,False,김천,0,-1,NaN
33,2022-10-01,토,16:30,인천,파이널A,9251,True,울산,0,-3,NaN
34,2022-10-08,토,19:00,춘천,파이널A,3751,False,강원,0,0,NaN
35,2022-10-11,화,19:30,인천,파이널A,2970,True,제주,3,2,NaN
36,2022-10-16,일,19:00,인천,파이널A,7592,True,포항,1,0,NaN

In [270]:
schedule.weekday.value_counts() # 주말위주의 경기일정 구성

토      16
일       8
공휴일     4
화       4
수       4
금       1
Name: weekday, dtype: int64

In [271]:
schedule.replace({'weekday': ['월', '화', '수', '목', '금']}, '평일' ,inplace=True) 
schedule.replace({'weekday': ['토', '일']}, '주말' ,inplace=True) # 데이터 갯수가 37개로, 너무 작기 때문에 카테고리를 최대한 줄여둔다

In [272]:
schedule.weekday.value_counts() # 3개의 카테고리

주말     24
평일      9
공휴일     4
Name: weekday, dtype: int64

In [273]:
schedule.game_time.value_counts() # 저녁시간대가 대부분

19:00    12
19:30     8
16:30     6
18:00     4
14:00     3
20:00     3
15:00     1
Name: game_time, dtype: int64

In [274]:
rank = pd.read_excel('dataset\\d95e264436cf42de.xlsx', engine='openpyxl')
rank.columns= ['game_date', 'ranking']
rank

     game_date  ranking
0   2019-03-03        5
1   2019-03-09        3
2   2019-03-10        5
3   2019-03-16        5
4   2019-03-17        6
..         ...      ...
322 2022-10-08        4
323 2022-10-09        4
324 2022-10-11        4
325 2022-10-12        4
326 2022-10-16        4

[327 rows x 2 columns]

In [275]:
schedule = pd.merge(schedule, rank, how='left', left_on='date', right_on='game_date')
schedule.drop(columns=['game_date','name'], inplace=True)
schedule

,date,weekday,game_time,field_name,game_type_name,audience,home,opponent,goal_incheon,goal_diff,ranking
0,2022-02-19,주말,16:30,인천,스플릿일반,5382,True,수원,1,1,2
1,2022-02-26,주말,14:00,인천,스플릿일반,4618,True,서울,1,0,4
2,2022-03-01,공휴일,16:30,강릉,스플릿일반,1559,False,강원,1,1,2
3,2022-03-05,주말,19:00,인천,스플릿일반,3581,True,포항,0,-1,4
4,2022-03-13,주말,14:00,인천,스플릿일반,2607,True,김천,1,1,3
5,2022-03-20,주말,19:00,탄천,스플릿일반,1361,False,성남,1,1,2
6,2022-04-02,주말,14:00,인천,스플릿일반,7054,True,울산,1,0,2
7,2022-04-05,평일,19:30,대구전,스플릿일반,3009,False,대구,2,1,2
8,2022-04-10,주말,16:30,인천,스플릿일반,5234,True,제주,2,0,2
9,2022-05-05,공휴일,19:00,수원,스플릿일반,3794,False,수원FC,2,0,2
10,2022-05-08,공휴일,16:30,인천,스플릿일반,7597,True,전북,0,-1,4
11,2022-05-14,주말,19:00,문수,스플릿일반,8351,False,울산,2,0,2
12,2022-05-17,평일,19:30,인천,스플릿일반,2754,True,대구,2,0,3
13,2022-05-21,주말,18:00,포항,스플릿일반,4824,False,포항,0,-2,5
14,2022-05-29,주말,16:30,인천,스플릿일반,6119,True,성남,1,1,4
15,2022-06-18,주말,18:00,제주W,스플릿일반,4155,False,제주,1,-1,5
16,2022-06-22,평일,19:30,인천,스플릿일반,2509,True,강원,4,3,4
17,2022-06-25,주말,20:00,서울W,스플릿일반,10787,False,서울,1,0,4
18,2022-07-03,주말,19:30,수원W,스플릿일반,4325,False,수원,0,0,5
19,2022-07-06,평일,19:00,인천,스플릿일반,3647,True,수원FC,0,-1,5
20,2022-07-09,주말,19:00,전주W,스플릿일반,6666,False,전북,2,0,5
21,2022-07-16,주말,18:00,김천,스플릿일반,1096,False,김천,1,1,5
22,2022-07-30,주말,20:00,탄천,스플릿일반,1861,False,성남,1,-2,5
23,2022-08-03,평일,19:00,인천,스플릿일반,3731,True,수원FC,1,0,5
24,2022-08-07,주말,19:30,대구전,스플릿일반,6336,False,대구,3,1,4
25,2022-08-13,주말,19:30,인천,스플릿일반,6339,True,전북,3,2,4
26,2022-08-20,주말,18:00,포항,스플릿일반,3479,False,포항,1,0,4
27,2022-08-27,주말,20:00,인천,스플릿일반,10139,True,서울,2,2,3
28,2022-09-02,평일,19:30,인천,스플릿일반,4372,True,강원,0,-1,4
29,2022-09-06,평일,19:00,제주W,스플릿일반,1688,False,제주,1,1,4
30,2022-09-11,공휴일,19:00,수원W,스플릿일반,8491,False,수원,3,0,4
31,2022-09-14,평일,19:00,인천,스플릿일반,4472,True,울산,0,0,4
32,2022-09-18,주말,15:00,김천,스플릿일반,1260,False,김천,0,-1,4
33,2022-10-01,주말,16:30,인천,파이널A,9251,True,울산,0,-3,4
34,2022-10-08,주말,19:00,춘천,파이널A,3751,False,강원,0,0,4
35,2022-10-11,평일,19:30,인천,파이널A,2970,True,제주,3,2,4
36,2022-10-16,주말,19:00,인천,파이널A,7592,True,포항,1,0,4

In [276]:
schedule.to_csv('C:\\Develop\\Project7\\dataproc\\schedule2022.csv')

# 클라이언트 리그 순위

In [277]:
rank = pd.read_excel('dataset\d95e264436cf42de.xlsx', engine='openpyxl')

In [278]:
rank

    2019-03-02 00:00:00  4
0            2019-03-03  5
1            2019-03-09  3
2            2019-03-10  5
3            2019-03-16  5
4            2019-03-17  6
..                  ... ..
322          2022-10-08  4
323          2022-10-09  4
324          2022-10-11  4
325          2022-10-12  4
326          2022-10-16  4

[327 rows x 2 columns]