In [102]:
import pandas as pd
import datetime

schedule = pd.read_csv('C:\\Develop\\Project7\\dataproc\\schedule2022.csv', usecols=['date', 'weekday', 'ranking'])
schedule.date = pd.to_datetime(schedule.date)
days = schedule.date.dt.strftime('%Y%m%d').values
days

array(['20220219', '20220226', '20220301', '20220305', '20220313',
       '20220320', '20220402', '20220405', '20220410', '20220505',
       '20220508', '20220514', '20220517', '20220521', '20220529',
       '20220618', '20220622', '20220625', '20220703', '20220706',
       '20220709', '20220716', '20220730', '20220803', '20220807',
       '20220813', '20220820', '20220827', '20220902', '20220906',
       '20220911', '20220914', '20220918', '20221001', '20221008',
       '20221011', '20221016'], dtype=object)

In [103]:
import pandas as pd
import json
import requests
from bs4 import BeautifulSoup

url = 'http://apis.data.go.kr/1360000/AsosDalyInfoService/getWthrDataList'

df = pd.DataFrame(columns=['stnId','tm','avgTa','sumRn'])
for day in days:
    queryParams = '?' + \
                'ServiceKey=' + 'YeSiYlUdLxSa9aOaPFM1kADTX45LzrMBd%2F43zl9fzjusryc9kIaewAPe9FmIZU5h09iiB4SFHX1UKe9jLQcSRw%3D%3D'+ \
                '&pageNo='+ '1' + \
                '&numOfRows='+ '999' + \
                '&dataType='+ 'JSON' + \
                '&dataCd='+ 'ASOS' + \
                '&dateCd='+ 'DAY' + \
                '&startDt='+ day + \
                '&endDt='+ day + \
                '&stnIds='+ '112'

    result = requests.get(url + queryParams)
    js = json.loads(result.content)
    data = pd.DataFrame(js['response']['body']['items']['item'])
    li = ['stnId','tm','avgTa','sumRn']
    data.loc[:,li]
    df = pd.concat((df,data.loc[:,li]),sort=False)

In [104]:
df = df[['tm', 'avgTa', 'sumRn']]

In [105]:
df.sumRn = df.sumRn.replace('',0)
df = df.rename(columns={'tm':'date','avgTa':'avgtemp','sumRn':'rainfall'})
df

         date avgtemp rainfall
0  2022-02-19    -1.7      0.0
0  2022-02-26     4.1      0.5
0  2022-03-01     4.8      4.3
0  2022-03-05     2.0        0
0  2022-03-13    10.0     32.8
0  2022-03-20     4.5        0
0  2022-04-02     6.8        0
0  2022-04-05     8.9        0
0  2022-04-10    16.7        0
0  2022-05-05    17.2        0
0  2022-05-08    15.2      0.7
0  2022-05-14    14.4        0
0  2022-05-17    17.4        0
0  2022-05-21    17.1        0
0  2022-05-29    20.0        0
0  2022-06-18    22.0        0
0  2022-06-22    22.9        0
0  2022-06-25    23.7        0
0  2022-07-03    27.1        0
0  2022-07-06    29.0        0
0  2022-07-09    25.3        0
0  2022-07-16    24.4        0
0  2022-07-30    31.1      0.0
0  2022-08-03    26.3     51.1
0  2022-08-07    28.1      0.0
0  2022-08-13    24.6      6.5
0  2022-08-20    26.7        0
0  2022-08-27    21.4      0.0
0  2022-09-02    25.1        0
0  2022-09-06    20.9     25.5
0  2022-09-11    22.7      0.0
0  2022-09-14    24.4      0.0
0  2022-09-18    25.8        0
0  2022-10-01    19.6        0
0  2022-10-08    16.2        0
0  2022-10-11    11.1        0
0  2022-10-16    16.3        0

In [106]:
df.to_csv('dataproc\\weather.csv')